_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -c ./ rapidfire
queue: gpu
nodes: 1
ntasks_per_node: 4
gpus_per_task: 1
job_name: atomate2FW
walltime: '24:00:00'
pre_rocket: |
          #SBATCH --exclusive
          ulimit -s unlimited
          module purge
          module load vasp
          export OMP_NUM_THREADS=1
post_rocket: null
logdir: ../logs